---
# Prefill Cluster
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: lws-deepseek-v3-2-prefill
spec:
  replicas: 1
  leaderWorkerTemplate:
    size: 2
    restartPolicy: None
    leaderTemplate:
      metadata:
        labels:
          role: leader
          phase: prefill
      spec: &prefill-spec
        priorityClassName: high-priority-100
        nodeSelector:
          # node.kubernetes.io/instance-type: p5en.48xlarge
          node.kubernetes.io/instance-type: p5.48xlarge
        tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
        containers:
        - name: sglang-prefill-leader
          image: &prefill-image 985955614379.dkr.ecr.us-west-2.amazonaws.com/sglang-efa-p5:v0.5.7-nixl
          imagePullPolicy: Always
          command: [ "python3", "-m", "sglang.launch_server" ]
          args: &prefill-args
            - "--model-path=deepseek-ai/DeepSeek-V3.2"
            - "--host=0.0.0.0"
            - "--port=30000"
            - "--tp-size=16"
            # - "--dp-size=2"
            - "--quantization=fp8"
            - "--mem-fraction-static=0.85"
            - "--disable-custom-all-reduce"
            - "--attention-backend=flashinfer"
            - "--trust-remote-code"
            - "--enable-nccl-nvls"
            - "--enable-p2p-check"
            - "--enable-dp-attention"
            - "--dist-init-addr=$(LWS_LEADER_ADDRESS):5000"
            - "--nnodes=$(LWS_GROUP_SIZE)"
            - "--node-rank=$(LWS_WORKER_INDEX)"
            - "--disaggregation-mode=prefill"
            - "--disaggregation-transfer-backend=nixl"
            # - "--load-balance-method=round_robin" # only when dp>1
          env: &prefill-env
            - name: LWS_WORKER_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['leaderworkerset.sigs.k8s.io/worker-index']
            - name: NCCL_DEBUG
              value: "INFO"
            - name: NCCL_SOCKET_IFNAME
              value: "eth0"
            - name: NCCL_P2P_DISABLE
              value: "0"
            - name: NCCL_P2P_LEVEL
              value: "NVL"
            - name: FI_PROVIDER
              value: "efa"
            - name: FI_EFA_USE_DEVICE_RDMA
              value: "1"
            - name: NCCL_NET_PLUGIN
              value: "ofi"
            - name: NCCL_TUNER_PLUGIN
              value: "ofi"
            - name: SGLANG_ENABLE_JIT_DEEPGEMM
              value: "0"
            - name: SGLANG_JIT_DEEPGEMM_PRECOMPILE
              value: "0"
          ports: &prefill-ports
            - name: http
              containerPort: 30000
            - name: nccl
              containerPort: 5000
            - name: bootstrap
              containerPort: 8998
          resources: &prefill-resources
            limits:
              vpc.amazonaws.com/efa: "16"
              nvidia.com/gpu: "8"
          volumeMounts: &prefill-volume-mounts
            - name: efa-devices
              mountPath: /dev/infiniband
            - name: cache-volume
              mountPath: /root/.cache/huggingface
            - name: shm
              mountPath: /dev/shm
          securityContext: &prefill-security-context
            privileged: true
            capabilities:
              add:
              - IPC_LOCK
              - SYS_RESOURCE
              - SYS_ADMIN
          startupProbe: &prefill-startup-probe
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 150
          livenessProbe: &prefill-liveness-probe
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 5
          readinessProbe: &prefill-readiness-probe
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
        volumes: &prefill-volumes
          - name: efa-devices
            hostPath:
              path: /dev/infiniband
              type: Directory
          - name: cache-volume
            hostPath:
              path: /mnt/k8s-disks/0/models/deepseek
              type: DirectoryOrCreate
          - name: shm
            emptyDir:
              medium: Memory
              sizeLimit: "500Gi"
    workerTemplate:
      spec:
        <<: *prefill-spec
        containers:
        - name: sglang-prefill-worker
          image: *prefill-image
          imagePullPolicy: Always
          command: [ "python3", "-m", "sglang.launch_server" ]
          args: *prefill-args
          env: *prefill-env
          ports: *prefill-ports
          resources: *prefill-resources
          volumeMounts: *prefill-volume-mounts
          securityContext: *prefill-security-context
          startupProbe: *prefill-startup-probe
          livenessProbe: *prefill-liveness-probe
          readinessProbe: *prefill-readiness-probe
        volumes: *prefill-volumes
---
# Decode Cluster
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: lws-deepseek-v3-2-decode
spec:
  replicas: 1
  leaderWorkerTemplate:
    size: 2
    restartPolicy: None
    leaderTemplate:
      metadata:
        labels:
          role: leader
          phase: decode
      spec: &decode-spec
        priorityClassName: high-priority-100
        nodeSelector:
          node.kubernetes.io/instance-type: p5.48xlarge
        tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
        containers:
        - name: sglang-decode-leader
          image: &decode-image 985955614379.dkr.ecr.us-west-2.amazonaws.com/sglang-efa-p5:v0.5.7-nixl
          imagePullPolicy: Always
          command: [ "python3", "-m", "sglang.launch_server" ]
          args: &decode-args
            - "--model-path=deepseek-ai/DeepSeek-V3.2"
            - "--host=0.0.0.0"
            - "--port=30001"
            - "--tp-size=16"
            # - "--dp-size=2"
            - "--quantization=fp8"
            - "--mem-fraction-static=0.85"
            - "--disable-custom-all-reduce"
            - "--attention-backend=flashinfer"
            - "--trust-remote-code"
            - "--enable-nccl-nvls"
            - "--enable-p2p-check"
            - "--enable-dp-attention"
            - "--dist-init-addr=$(LWS_LEADER_ADDRESS):5000"
            - "--nnodes=$(LWS_GROUP_SIZE)"
            - "--node-rank=$(LWS_WORKER_INDEX)"
            - "--disaggregation-mode=decode"
            - "--disaggregation-transfer-backend=nixl"
            - "--max-running-requests=128"
            # - "--prefill-round-robin-balance" # only when dp>1
          env: &decode-env
            - name: LWS_WORKER_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['leaderworkerset.sigs.k8s.io/worker-index']
            - name: NCCL_DEBUG
              value: "INFO"
            - name: NCCL_SOCKET_IFNAME
              value: "eth0"
            - name: NCCL_P2P_DISABLE
              value: "0"
            - name: NCCL_P2P_LEVEL
              value: "NVL"
            - name: FI_PROVIDER
              value: "efa"
            - name: FI_EFA_USE_DEVICE_RDMA
              value: "1"
            - name: NCCL_NET_PLUGIN
              value: "ofi"
            - name: NCCL_TUNER_PLUGIN
              value: "ofi"
            - name: SGLANG_ENABLE_JIT_DEEPGEMM
              value: "0"
            - name: SGLANG_JIT_DEEPGEMM_PRECOMPILE
              value: "0"
          ports: &decode-ports
            - name: http
              containerPort: 30001
            - name: nccl
              containerPort: 5000
          resources: &decode-resources
            limits:
              vpc.amazonaws.com/efa: "16"
              nvidia.com/gpu: "8"
          volumeMounts: &decode-volume-mounts
            - name: efa-devices
              mountPath: /dev/infiniband
            - name: cache-volume
              mountPath: /root/.cache/huggingface
            - name: shm
              mountPath: /dev/shm
          securityContext: &decode-security-context
            privileged: true
            capabilities:
              add:
              - IPC_LOCK
              - SYS_RESOURCE
              - SYS_ADMIN
          startupProbe: &decode-startup-probe
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 150
          livenessProbe: &decode-liveness-probe
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 5
          readinessProbe: &decode-readiness-probe
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
        volumes: &decode-volumes
          - name: efa-devices
            hostPath:
              path: /dev/infiniband
              type: Directory
          - name: cache-volume
            hostPath:
              path: /mnt/k8s-disks/0/models/deepseek
              type: DirectoryOrCreate
          - name: shm
            emptyDir:
              medium: Memory
              sizeLimit: "500Gi"
    workerTemplate:
      spec:
        <<: *decode-spec
        containers:
        - name: sglang-decode-worker
          image: *decode-image
          imagePullPolicy: Always
          command: [ "python3", "-m", "sglang.launch_server" ]
          args: *decode-args
          env: *decode-env
          ports: *decode-ports
          resources: *decode-resources
          volumeMounts: *decode-volume-mounts
          securityContext: *decode-security-context
          startupProbe: *decode-startup-probe
          livenessProbe: *decode-liveness-probe
          readinessProbe: *decode-readiness-probe
        volumes: *decode-volumes
---
# Services
apiVersion: v1
kind: Service
metadata:
  name: deepseek-v3-2-prefill
spec:
  selector:
    leaderworkerset.sigs.k8s.io/name: lws-deepseek-v3-2-prefill
    role: leader
  ports:
  - name: http
    protocol: TCP
    port: 30000
    targetPort: http
  - name: nccl
    protocol: TCP
    port: 5000
    targetPort: nccl
  - name: bootstrap
    protocol: TCP
    port: 8998
    targetPort: bootstrap
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: deepseek-v3-2-decode
spec:
  selector:
    leaderworkerset.sigs.k8s.io/name: lws-deepseek-v3-2-decode
    role: leader
  ports:
  - name: http
    protocol: TCP
    port: 30001
    targetPort: http
  - name: nccl
    protocol: TCP
    port: 5000
    targetPort: nccl
  type: ClusterIP
---
# Router Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sglang-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sglang-router
  template:
    metadata:
      labels:
        app: sglang-router
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      initContainers:
      - name: wait-for-backends
        image: curlimages/curl:latest
        env:
        - name: PREFILL_URL
          value: "http://deepseek-v3-2-prefill:30000"
        - name: DECODE_URL
          value: "http://deepseek-v3-2-decode:30001"
        command:
        - sh
        - -c
        - |
          echo "Waiting for prefill and decode backends to be healthy..."
          echo "Prefill URL: ${PREFILL_URL}"
          echo "Decode URL: ${DECODE_URL}"
          MAX_WAIT=2400  # 40 minutes for cold starts
          ELAPSED=0

          while [ $ELAPSED -lt $MAX_WAIT ]; do
            PREFILL_OK=0
            DECODE_OK=0

            if curl -f -m 5 ${PREFILL_URL}/health 2>/dev/null; then
              echo "✓ Prefill backend is healthy"
              PREFILL_OK=1
            else
              echo "✗ Prefill backend not ready yet..."
            fi

            if curl -f -m 5 ${DECODE_URL}/health 2>/dev/null; then
              echo "✓ Decode backend is healthy"
              DECODE_OK=1
            else
              echo "✗ Decode backend not ready yet..."
            fi

            if [ $PREFILL_OK -eq 1 ] && [ $DECODE_OK -eq 1 ]; then
              echo "✓ All backends are healthy! Starting router..."
              exit 0
            fi

            sleep 10
            ELAPSED=$((ELAPSED + 10))
          done

          echo "✗ Timeout waiting for backends after ${MAX_WAIT}s"
          exit 1
      containers:
      - name: router
        image: 985955614379.dkr.ecr.us-west-2.amazonaws.com/sglang-efa-p5:v0.5.7-nixl
        command: [ "python3", "-m", "sglang_router.launch_router" ]
        env:
        - name: PREFILL_URL
          value: "http://deepseek-v3-2-prefill:30000"
        - name: DECODE_URL
          value: "http://deepseek-v3-2-decode:30001"
        args:
        - "--pd-disaggregation"
        - "--prefill=$(PREFILL_URL)"
        - "--decode=$(DECODE_URL)"
        - "--host=0.0.0.0"
        - "--port=8000"
        ports:
        - name: http
          containerPort: 8000
        startupProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /v1/models
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 18
---
apiVersion: v1
kind: Service
metadata:
  name: sglang-router
spec:
  selector:
    app: sglang-router
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  type: ClusterIP
